port: 19522
database:
  master:
    ip: localhost
    username: root
    password: 123456
    port: 3306
    base: practice
  slave:
    ip: localhost
    username: root
    password: 123456
    port: 3306
    base: practice2