spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.practice.domain.dao.po
