server:
  port: ${port}

spring:
  profiles:
    active: dev

  datasource:
#    url: jdbc:mysql://${database.master.ip}:${database.master.port}/${database.master.base}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: ${database.master.username}
#    password: ${database.master.password}
    # master
    master:
      jdbc-url: jdbc:mysql://${database.master.ip}:${database.master.port}/${database.master.base}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: ${database.master.username}
      password: ${database.master.password}

    # slave
    slave:
      jdbc-url: jdbc:mysql://${database.slave.ip}:${database.slave.port}/${database.slave.base}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: ${database.slave.username}
      password: ${database.slave.password}
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.practice.domain.dao.po
  configuration:
    # 不启用二级缓存，原因是连表查询会有问题
    cache-enabled: false
    # 查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: true
    # 设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指定)，不会加载关联表的所有字段，以提高性能
    aggressive-lazy-loading: false
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 允许使用列标签代替列名
    use-column-label: true
    # 允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    use-generated-keys: true
    # 给予被嵌套的resultMap以字段-属性的映射支持(NONE, PARTIAL, FULL)
    auto-mapping-behavior: FULL
    # 配置默认的执行器，SIMPLE 执行器没有什么特别之处，REUSE 执行器重用预处理语句，BATCH 执行器重用语句和批量更新
    default-executor-type: REUSE
    # 据库超过180秒仍未响应则超时
    default-statement-timeout: 180
    # 是否启用下划线与驼峰式命名规则的映射（如first_name => firstName）
    map-underscore-to-camel-case: true
    # 不使用SESSION，原因是多个服务器时会出现问题
    default-fetch-size: 200
    local-cache-scope: STATEMENT
    jdbc-type-for-null: OTHER
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    log-prefix: mybatis.sql.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.practice.domain.dao.mapper: DEBUG # 指定日志级别


